[package]
name = "ilgda-ipc"
version = "0.1.3"
edition = "2021"
authors = ["NightMare-Vortex"]
description = "IPC standard used for ilgda"
license = "MIT"
repository = "https://github.com/NightMare-Vortex/ilgda-ipc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.simdutf8]
version = "0.1.4"
features = ["hints", "aarch64_neon", "aarch64_neon_prefetch"]
path = "./crates/simdutf8"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytemuck = { version = "1.14.0", features = ["must_cast", "min_const_generics"] }
paste = "1"