[package]
name = "ilgda-ipc"
version = "0.1.3"
edition = "2021"
authors = ["NightMare-Vortex"]
description = "IPC standard used for ilgda"
license = "MIT"
repository = "https://github.com/NightMare-Vortex/ilgda-ipc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
tokio = ["dep:tokio"]

[dependencies]
tokio = { version = "1", features = ["full"], optional = true }
bytes = "1.4.0"
paste = "1"